import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/providers";

import initTranslations from "../i18n";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  params: { locale: string };
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<Props>) {

  const { t, resources } = await initTranslations(locale); // Server-side use example

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Providers locale={locale} resources={resources}>{children}</Providers>
      </body>
    </html>
  );
}
